### ISSUE TITLE
Optimizing h in growthrates

### ISSUE THREAD

**Issue by bznes** [tpetzoldt/growthrates#2]
Hi.  I'll start with saying this is a very handy package.  I'm using the growthrates package to pull lag time and growth rate for a very large number of bacterial growth curves.  Currently I'm using fit_easylinear for these models and I'm wondering how to optimize h.  I imagine this varies based on the time step and number of points in the exponential part of the growth curves.  I've plotted the fits for a range of h and "eyeballed" a best number to hit the exponential region but is there a means to pull fit data from the results?  I've been able to pull summary(model), residuals(model) for single fits but was wondering if there is a better way to select this value.  I may be off on the best test for comparison but anova(model_h7,model_h10) or AIC(model_h7,model_h10) doesn't work with that output.  Any direction would be greatly appreciated.

Thanks!

**Comment by echse** [comment]
Hi, I guess your growth curves exhibit substantial variation in the number of data points that represent the exponential part of the curve. Instead of trying to optimize "h" in "fit_easylinear", wouldn't it be easier to use "fit_ growthmodel"? Without knowing details, I would suggest to start with a logistic model to get a feeling for the concept. Finally, you can try a more complex growth model that is capable of fitting a lag phase. I sometimes experienced problems with parameter identifyability in sophisticated lag-phase models. A simple alternative might be Eqn. 4 in this paper:
https://doi.org/10.1016/j.plasmid.2018.12.003
I used that formulation to automatically fit > 10^4 growth curves (not using this package, however).

**Comment by tpetzoldt** [comment]
I agree with echse. fit_easylinear is a very useful heuristic method. I would not use anova or AIC in that case, but would recommend parametric models (fit_growthmodel) instead.
