### ISSUE TITLE
Customizing GrowthRates plot (ylab and xlab)

### ISSUE THREAD

**Issue by Pereiraehs** [tpetzoldt/growthrates#3]
Hi! First, I'd like to thank the pack it is bringing lot of help to my project. 
Now, I started recently with R and I would like to customize the graphic. I was trying to change Y and X axes titles but it didn't work.

fitA5 <- fit_easylinear(Plate$Time, Plate$A5, h = 10, quota = 0.95)
plot (fitA5, log = "y")
title(main="Curve", col.main="black", font.main=4)
title(xlab="DO600")
title(ylab="Time(h)")   

The title is over the original title - that is still there -. Anyway to edit the axes? 

Thnks

**Comment by tpetzoldt** [comment]
Dear Henrique,

many thanks for the feedback. The built-in plot functions are intended 
to produce quick output "as is". They have limited support for 
customization, because it is always possible to create own user-defined 
plots in R according to your personal needs and style. This is a typical 
approach for many R packages.

Nevertheless, I'll take your wish as a suggestion and will think about 
more flexible graphics for the next release.

For the moment, just use the "myplot.R" function below.

Hope it helps,

Thomas

---
myplot <- function(x, log=log, ...){
  obs <- obs(x)

  plot(obs[,"y"] ~ obs[,"time"],
       log=log, ...)
  points(obs[x@ndx,"y"] ~ obs[x@ndx,"time"], pch=16, col="red")

  ## lag phase
  lag <- coef(x)["lag"]

  time <- seq(min(obs[,"time"] + lag), max(obs[,"time"]), length=200)
  coef_ <- coef(x)
  lines(time, x@FUN(time, c(y0=unname(coef_["y0_lm"]), mumax=unname(coef_["mumax"])))[,"y"], ...)

  ## todo: use estimated or averaged y0_data instead of y[1]
  lines(c(min(obs[1, "time"]), lag), rep(obs[1, "y"], 2), lty="dotted")
}

library(growthrates)
source("myplot.R")
splitted.data <- multisplit(bactgrowth, c("strain", "conc", "replicate"))
dat <- splitted.data[[1]]

plot(value ~ time, data=dat)
fit <- fit_easylinear(dat$time, dat$value)

myplot(fit, log="y", xlab="", ylab="")

title(main="Curve", col.main="black", font.main=4)
title(xlab="DO600")
title(ylab="Time(h)")

**Comment by Pereiraehs** [comment]
Thank you!
